### ISSUE TITLE
crash when GL_RENDERER is GDI Generic

### ISSUE THREAD

**Issue by bvanevery** [cr88192/bgbtech_engine#1]
engine0.exe works fine on a Windows 7 machine with low end AMD integrated graphics, and on a Windows 10 machine with a GeForce 8600M GT.  However on a Windows 10 machine with only Mobile Intel (R) 4 Series Express Chipset graphics, engine0.exe crashes immediately.  It does produce a log file.  When I upgraded this 2008 era machine to Windows 10, I remember that Intel had declined to make a HW accelerated driver for Windows 10 that supported OpenGL, since it was so old.  GPU Caps Viewer gives the following info:

GL_RENDERER GDI Generic
GL_VERSION 1.1.0
GLSL version n.a.
OpenGL extensions: 2 (GL=2, WGL=0)
GL_EXT_BGRA (OpenGL 1.2)
GL_WIN_swap_hint

You may not encounter too many such minimalist OpenGL machines in the wild, but you should have a path that detects this case and gracefully exists, rather than crashing.  I will say that otherwise, this machine has run Windows 10 just fine.  So it's not inconceivable that others will successfully upgrade old machines to Windows 10, while it's still free to do so.

Intel OpenGL drivers of the 2008 era were really really bad.  Generally you had to deploy with DirectX.

GPU Caps Viewer has a "more caps" section where more stuff is reported.  Piles of those fields are 0's.  GL_VERSION_1_1 and GL_VERSION_1_2 are the only things with nonzero fields.

**Comment by cr88192** [comment]
Can't test directly, but should be fixed.
Using with lower-end stats should be possible by editing 'resource/game/default.cfg', and the engine seems basically usable with software rendering on my end.

**Comment by bvanevery** [comment]
Still crashes as before.  Log attached.
[bgbgc_log.txt](https://github.com/cr88192/bgbtech_engine/files/42243/bgbgc_log.txt)

**Comment by cr88192** [comment]
dunno. have you checked if Visual Studio Debugger can show anything. the logs don't show much that can help in this case, as I normally use the debugger to catch crashes, and don't have a direct analog of your PC.

if the PDB's don't work, I can start removing them to save space.

**Comment by bvanevery** [comment]
Whatever you did, latest pull does run on the GDI Generic machine now!  It's not without problems but this specific bug is closed.
